name: Build, Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'


      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest

    build: 
      runs-on: ubuntu-latest
      need: test
      if: success()
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2

        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Set Docker image tag
          id: tag
          run: echo "tag=$(date +%Y%m%d)-${{ github.sha }}" >> $GITHUB_ENV

      # # Build and push the Docker image
        - name: Build and Push Docker Image
          run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-sample-image:${{ env.tag }} .
            docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-sample-image:${{ env.tag }}


