name: Build, Push Docker Image, and Update Infra Repo

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      # Checkout the source code
      - name: Checkout source repository
        uses: actions/checkout@v3

    #   # Log in to Docker Hub
    #   - name: Log in to Docker Hub
    #     uses: docker/login-action@v2
    #     with:
    #       username: ${{ secrets.DOCKER_USERNAME }}
    #       password: ${{ secrets.DOCKER_PASSWORD }}

      # Generate a unique tag
      - name: Set Docker image tag
        id: tag
        run: | 
            ls -a
            echo "tag=$(date +%Y%m%d)-${{ github.sha }}" >> $GITHUB_ENV
            printenv
                
     

