name: Build, Push Docker Image, and Update Infra Repo

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      # Checkout the source code
      - name: Checkout source repository
        uses: actions/checkout@v3

    #   # Log in to Docker Hub
    #   - name: Log in to Docker Hub
    #     uses: docker/login-action@v2
    #     with:
    #       username: ${{ secrets.DOCKER_USERNAME }}
    #       password: ${{ secrets.DOCKER_PASSWORD }}

      # Generate a unique tag
      - name: Set Docker image tag
        id: tag
        run: | 
            ls -a
            echo "tag=$(date +%Y%m%d)-${{ github.sha }}" >> $GITHUB_ENV
            printenv
            echo "*************"
            echo "tag=$tag"  # Access the tag directly within the step (before writing to $GITHUB_ENV)
            echo "GITHUB_SHA=${{ github.sha }}"  # Access the github.sha directly
            echo "*************"
            echo "$GITHUB_ENV"  # Print contents of the $GITHUB_ENV file (path)
            echo "0000000"
            echo "$GITHUB_REF"  # Example of another GitHub variable
            echo "$env"  # This will be empty unless 'env' is explicitly set in the workflow
            echo "$env.tag"  # Will be empty in the current step, as 'env' is not set for this context
        
      - name: another step
        id : ggboi
        run : |
            echo "$env.tag" 
            
     

