name: Test, Build, Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest

  building:
    runs-on: ubuntu-latest
    needs: test  # This job runs only after 'test' job completes successfully
    environment: production
    if: success() 
    env:
      IMAGE_NAME: fastapi-sample-image
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Docker image tag
        id: tag
        run: echo "tag=$(date +%Y%m%d)-${{ github.sha }}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.tag }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.tag }}

      - name: Clone the Infra repo
        run: | 
            git clone https://github.com/MercyShark/infra-repo.git
            git config --global user.email "prajapatirishabh04@gmail.com"
            git config --global user.name "GITHUB ACTIONS"
            cd infra-repo

      - name: Update Docker Image tag in infra rep depl file
        run: |
          ls
          cd infra-repo
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.tag }}|" depl.yaml
          git add .
          git commit -m "Updated docker image tag to ${{ env.tag }}"
          git push https://x-access-token:${{ secrets.ACCESS_TOKEN_FOR_INFRA }}@github.com/MercyShark>/infra-repo.git